url: "https://notes.99000000.xyz"
exclude: 
- template/
- fixing.epub
- docs/, LICENSE
- "broken links output.md"
- assets/*.xcf
- /*.sh
- docs.tar.xz
- Everything.canvas
include: [.nojekyll]
destination: docs/

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
  - scope:
      path: "notes/"
    values:
      layout: "default"
  - scope:
      path: "articles/"
    values:
      css: "default"

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%Y-%m-%d'
