- alias: spicata.99000000.xyz
  link: 

- alias: mint fresh notes
  link: mint-fresh-notes

- alias: my stories about the town
  link: towns

- alias: only nine lives
  link: onl

- alias: So, you want a website...
  link: web